# Set sleep timeout to 30min (30*60*1000ms)
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=1800000

# Enable mouse
CONFIG_ZMK_MOUSE=y

CONFIG_ZMK_KEYBOARD_NAME="LP Corne"

# Enable display
CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_WIDGET_BATTERY_STATUS_SHOW_PERCENTAGE=y
